stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Train


  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - img_size
      - channels
      - loss
      - learning_rate
    outs:
      - artifacts/base_model



  training:
    cmd: python src/cnnClassifier/pipeline/stage_03_training.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_training.py
      - src/cnnClassifier/components/callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/Train/Train
      - artifacts/base_model
    params:
      - img_size
      - channels
      - color
      - epochs
      - batch_size
      - learning_rate
      - loss
    outs:
      - artifacts/training/trained_model.keras




  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_04_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Train/Train
      - artifacts/training/trained_model.keras
    params:
      - test_batch_size
      - batch_size
      - img_size
      - channels
      - color
    metrics:
    - scores.json:
        cache: false