img_size : [224, 224]
channels : 3
batch_size : 40   # set batch size for training
epochs : 40   # number of all epochs in training
patience : 1   #number of epochs to wait to adjust lr if monitored value does not improve
stop_patience : 3   # number of epochs to wait before stopping training if monitored value does not improve
threshold : 0.9   # if train accuracy is < threshold adjust monitor accuracy, else monitor validation loss
factor : 0.5   # factor to reduce lr by
ask_epoch : 5   # number of epochs to run before asking if you want to halt training