artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://file.io/XiuVnBHpIZxF
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/Train/
  data_dir: artifacts/data_ingestion/Train/Train
  csv_dir: artifacts/data_ingestion/Train/train_data.csv


base_model:
  base_model_dir: artifacts/base_model
  base_model_path: artifacts/base_model/base_model.keras

callbacks:
  root_dir: artifacts/callbacks
  tensorboard_root_log_dir: artifacts/callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/callbacks/checkpoint_dir/model.keras

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/trained_model.keras
  base_model_path: artifacts/base_model/base_model.keras
  data_dir: artifacts/data_ingestion/Train/Train
  csv_dir: artifacts/data_ingestion/Train/train_data.csv
  data_gen_path: artifacts/training