artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://file.io/XiuVnBHpIZxF
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/Train/
  data_dir: artifacts/data_ingestion/Train/Train
  csv_dir: artifacts/data_ingestion/Train/train_data.csv


model:
  model_dir: artifacts/model
  model_path: artifacts/model/my_model.h5

callbacks:
  root_dir: artifacts/callbacks
  tensorboard_root_log_dir: artifacts/callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/callbacks/checkpoint_dir/model.h5